### ISSUE TITLE
The weight of images in Middlebury train set.

### ISSUE THREAD

**Issue by wuzhongwulidong** [waychin-weiqin/ITSA#2]
Great work! 
However I find some confusing operations in the eval.py file:
            if imgName in ['PianoL', 'Playroom', 'Playtable', 'Shelves', 'Vintage']:
                d1_err = d1_err * 0.5

So, why give these five images in Middlebury the weight 0.5 in calculating the overall 2-pixel Error?

Another confusion, as shown in Table 4 in the paper, the performance of ITSA-CFNet on KITTI, i.e. KITTI12 3-pixel=4.2, and KITTI15 3-pixel=4.7,  Are they actually D1 metric or 3-pixel Error?  I found they should be D1 metric according to eval.py, not 3-pixel Error as claimed below Table 4.  
Could you help us to confirm it? Thanks.

**Comment by waychin-weiqin** [comment]
Hi @wuzhongwulidong, thank you for the kind words. 

The weightings are according to the official Middlebury evaluation scheme, where the mentioned five images are weighted by 0.5. You can find this information from this [benchmark](https://vision.middlebury.edu/stereo/eval3/).

The results reported for KITTI (both 2012 and 2015) are the D1 error (not the 3-pixel error). Sorry for the confusion.

**Comment by wuzhongwulidong** [comment]
Hi @waychin-weiqin, I did not find the information about "the mentioned five images are weighted by 0.5". Could you point out its specific location on this [benchmark](https://vision.middlebury.edu/stereo/eval3/)? 
Thank you very much.

**Comment by waychin-weiqin** [comment]
Hi again @wuzhongwulidong. You can find the weights for each class on top of the benchmark (as shown in the snapshot below, where the weights are highlighted in the red box). This can also be found in their Matlab evaluation script. I hope this information is helpful :)

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/33308266/187019891-7c9427a3-5582-4d25-9f26-c1a9a01bbfcc.png">
